name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Execute Python script
        run: python action.py
        env:
          SHA256_SIGNING_SECRET: ${{ secrets.SHA256_SIGNING_SECRET }}